langserver/build_context.go, langserver/handler.go, langserver/integration_test.go, langserver/internal/refs/refs.go, langserver/internal/refs/refs_test.go, langserver/internal/refs/testdata/convoluted.go, langserver/internal/refs/testdata/defs.go, langserver/internal/refs/testdata/empty.go, langserver/internal/refs/testdata/http-request-headers.go, langserver/internal/refs/testdata/imports.go, langserver/internal/refs/testdata/vars.go, langserver/langserver_test.go, langserver/loader.go, langserver/references.go, langserver/symbol.go, langserver/workspace_refs.go, pkg/lspext/lspext.go
- Helps https://github.com/sourcegraph/sourcegraph/pull/1712#issuecomment-253357127
- See `pkg/lspext` for a concrete definition of this method.
=> Add `workspace/reference` akin to `workspace/symbol` but for external references

.travis.yml, langserver/hover.go, langserver/internal/refs/refs.go, langserver/internal/refs/refs_test.go, langserver/internal/refs/testdata/convoluted.go, langserver/internal/refs/testdata/unmatching-imports.go, langserver/langserver_test.go, langserver/workspace_refs.go
See individual commit messages for details.
=> Struct hover + workspace/reference output corrections

langserver/build_context.go
@shurcooL was testing out the go-langserver, and noticed that his multiple GOPATH environment was triggering an error when the server was initialized.
Question for the reviewer - is there a more "correct" way to check if the go file in question contains a given GOPATH than string contains?
=> langserver: support multiple gopaths

langserver/workspace_refs.go
This limits workspace/reference to using only one fourth of the CPU by default. This is because, currently, it is quite an intensive operation. Typically the operation is only ran in the background, so it running slower is OK but not when it is a detriment to every other LSP operation (which is often user-invoked).
Running with `WORKSPACE_REFERENCE_PARALLELISM=8` will retain the old behavior prior to this change.
=> langserver: limit workspace/reference to 1/4 CPU by default + add WORKSPACE_REFERENCE_PARALLELISM env var

langserver/handler.go
@slimsag did the hard work, I get to steal all the glory by adding the capability.
=> lsp: add doc symbol capability

brew/README.md, brew/generate.sh, brew/go-langserver.rb, brew/go-langserver.rb.template
Added script and template used to generate Homebrew formula
=> Homebrew formula generator

langserver/cmd/langserver-go/langserver-go.go, langserver/langserver_test.go
https://github.com/sourcegraph/jsonrpc2/pull/4
=> update to use latest github.com/sourcegraph/jsonrpc2

langserver/config.go, langserver/workspace_refs.go
Based on #88 (I will drop those commits once it is merged)
=> workspace/xreferences: optimizations; correct vendor handling; minor cleanups

langserver/handler.go, langserver/symbol.go
=> symbol: single-flight cache access

langserver/cache.go
The memory overhead of ARC in production is not worth it. This is an experiment
to use a very simple LRU. We will adjust this if we find in practice we have a
bad cache hit rate.
=> langserver: Use a simple LRU cache

langserver/cache.go
This likely won't be that useful in the long-term since we don't evict on server
shutdown. However, in the short-term it will give a good idea of cache growth
rate on server startup which is useful for understanding how to tune.
=> cache: Prometheus gauge for cache size

langserver/definition.go, langserver/langserver_test.go
Addresses: https://github.com/sourcegraph/go-langserver/issues/25
Allows: https://github.com/sourcegraph/sourcegraph/issues/3322
=> Send back the location of the identifier

langserver/ast.go, langserver/symbol.go
The LSP spec states the end of ranges are exclusive.
Fixes #7
=> symbol: Off-by-1 in range

langserver/cancel.go, langserver/cancel_test.go, langserver/handler.go, pkg/lsp/jsonrpc2.go, pkg/lsp/service.go
See spec at https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#cancelRequest
=> langserver: Add cancelRequest support

langserver/workspace_refs.go
The use of them prevents us from invoking `clearInfoFields(pkg)` and saving
memory (as seen in https://github.com/sourcegraph/go-langserver/pull/122)
and also can cause concurrent map accesses of `pkg.Info*`
=> langserver: do not use goroutines during AfterTypeCheck

langserver/references.go
The main goal I want to achieve is to start doing a typecheck with a potentially
out of date ImportGraph, and then follow up with typechecking an up to date
ImportGraph. To avoid doing extra work + being able to do it twice cleanly
required a bunch of refactoring. The next change should be clearer now.
My only concern in this change is the switch from collecting refs in
`[]*ast.Ident` batches, to sending each individual `*ast.Ident` down a channel.
This may have a negative impact on perf, but in practice I believe this will be
minor. In future we will only stream references as well, so this will be fine
when we don't have to build up the final result.
=> references: Major refactoring

langserver/fs.go
We still don't advertise we support this since I have not tested this
thoroughly. However, I am working on a PR now which refactors this logic to make
it more testable.
=> fs: Support incremental file updates

langserver/handler.go
Fixes https://github.com/sourcegraph/go-langserver/issues/147
=> langserver: Ignore initialized notification

langserver/fs.go, langserver/handler.go, langserver/loader_test.go
=> fs: Only invalidate cache if files change

langserver/references.go
=> references: Include declaration in stream

langserver/langserver_test.go, langserver/signature.go
=> Fixes #137 Add docs to signature help

main.go
See comment for process. Will be manual for now. Will release a v2 soon.
Fixes #154
=> Include -version flag in cmd

langserver/references.go
=> references: Respect limit when streaming

langserver/workspace_refs.go, pkg/lspext/lspext.go
=> Add Limit param to workspace/xreferences

langserver/handler.go
Currently we use an AsyncHandler, which means we could process didChange
requests out of order, depending on how the go runtime decides to schedule the
goroutines.
Fixes #155
=> Handle didChange requests in order

langserver/definition.go, langserver/hover.go, langserver/internal/godef/go/parser/parser.go, langserver/internal/godef/go/parser/parser_go18.go, langserver/internal/godef/go/parser/parser_go19.go, langserver/internal/godef/godef.go, langserver/langserver_go19_test.go, langserver/langserver_test.go, langserver/util.go
Fixes https://github.com/sourcegraph/go-langserver/issues/213
=> Support type aliases

langserver/hover.go, langserver/langserver_test.go
Fixes https://github.com/sourcegraph/go-langserver/issues/223
=> Include docs on methods for godef hover

langserver/completion.go
=> Make completion regex readable

langserver/util/os_windows.go
=> use correct package for os_windows.go

langserver/langserver_test.go, langserver/symbol.go
=> differentiate between interface and class symbols

langserver/references.go, langserver/util/util.go
I'm afraid this diff is hard to read. It is easier to grok if you do a (local) diff ignoring whitespace.
=> Parallelize findReferencesPkgLevel

langserver/internal/godef/go/parser/parser.go
=> Make godef work with go master

README.md, langserver/completion.go, langserver/config.go, langserver/definition.go, langserver/handler.go, langserver/hover.go, langserver/integration_test.go, langserver/langserver_test.go, langserver/lspx.go, langserver/symbol.go, main.go
Fixes https://github.com/sourcegraph/go-langserver/issues/280
cc @lloiser @Contextualist @ramya-rao-a
=> langserver: Support InitializationOptions

langserver/hover.go
It is possible for this to happen if typechecking for a package has failed, in which case the relevant information would be in diagnostics. This prevents a nil pointer deref of the `pkg` and informs the user.
=> langserver: return a hover error if importing package has failed

langserver/handler_common.go, langserver/util/util.go
=> Fixing file hier.

langserver/internal/gocode/gbimporter/gbimporter.go
this PR fixed #319
related: https://github.com/mdempsky/gocode/issues/47
=> gocode: Use go/importer as a fallback

langserver/handler.go
=> fix: set RenameProvider for rename

Dockerfile, buildkite.yml, deploy.sh
- Docker repository https://hub.docker.com/r/sourcegraph/lang-go
- Buildkite pipeline https://buildkite.com/sourcegraph/lang-go
=> Set up auto publishing of the sourcegraph/lang-go Docker image from master

README.md
Resolves https://github.com/sourcegraph/go-langserver/issues/367
=> Recommend gopls

appveyor.yml
=> Pin go 1.12 on appveyor

langserver/hover.go, langserver/integration_test.go
References https://github.com/sourcegraph/sourcegraph/issues/5383
=> Display values of constants onHover
