sourcegraph/go-langserver

langserver/symbol_test.go
This tests that exported symbols are prioritized over non-exported symbols, all else being equal.
=> symbol: unit test for exported sym ordering

langserver/workspace_refs.go
Previously we did a lot of work (typechecking and finding all external refs)
for vendor dependencies even though we would just throw out the results. By
not doing this work, we can transform the time it takes to invoke `workspace/reference`
for repos with many vendor dependencies drastically (e.g. prometheus goes
from ~5 mins -> 27s).
=> langserver: optimize handling of vendor dependencies for workspace/reference

langserver/definition.go, langserver/hover.go, langserver/langserver_test.go, langserver/loader.go, langserver/references.go
This makes it such that hovering over any symbol always provides the
relevant documentation for that symbol.
=> langserver: add documentation strings to textDocument/hover

langserver/handler.go, langserver/integration_test.go, langserver/langserver_test.go, langserver/symbol.go
`textDocument/documentSymbol` is a part of the LSP (https://github.com/sourcegraph/language-server-protocol/blob/master/protocol.md#document-symbols-request).
In particular, it is useful to us because of its similarity to `workspace/symbol` except restricted to a single file ('document'). This means that e.g. when redirecting from a code file's position -> def landing page we only have to ask for a single file's symbols in order to find the symbol's `Name, ContainerName` pair which identify it instead of every symbol in the workspace (in our case, repository). It's worth adding because, for large workspaces, it can change the time taken from ~15s -> 1s or so to perform this operation.
=> Implement textDocument/documentSymbol

langserver/build_context.go
It doesn't really make sense to override the release tags, and adding them in
allows us to analyse files with go version build tags. An example of a hover
that failed is at
https://sourcegraph.com/github.com/sourcegraph/go-langserver@08f9683e4a0dbacf97baaa6f4c0db1c685d7d86b/-/blob/langserver/loader.go#L232:2
It failed since loader.Config is behind a build tag. After this change it works.
Fixes https://github.com/sourcegraph/sourcegraph/issues/2036
=> Use build.Default's ReleaseTags if we override

langserver/definition.go
Update def range to be a position instead of a range. This fixes a bug
where a hover tooltip would only show one line when pressing cmd/ctrl,
instead of the entire definition.
This is the behavior of the most popular Go language server.
=> Fix def range

langserver/loader.go, langserver/util.go, langserver/workspace_refs.go
Prior to this change `workspace/reference` would individually typecheck each package
in the workspace that it intended to list external references for. This meant that
e.g. if a workspace had two packages `pkg/a` and `pkg/b` which both use `net/http`
that `net/http` and all of it's dependencies would have to be typechecked twice (once
for each input package, respectively).
After this change, we no longer cache typechecking results for workspace/reference
(in fact, it is not entirely useful to cache them due to workspace/reference being
a bad indicator of real direct user-initiated queries) and instead typecheck all
packages we intend to list external references of, together. This means that in the
prior example, `net/http` and it's dependencies will only be typechecked once. This
is …
=> langserver: significantly reduce the amount of typechecking for workspace/reference

langserver/symbol.go, langserver/vendor/README.md, langserver/vendor/go/doc/comment.go, langserver/vendor/go/doc/doc.go, langserver/vendor/go/doc/example.go, langserver/vendor/go/doc/exports.go, langserver/vendor/go/doc/filter.go, langserver/vendor/go/doc/headscan.go, langserver/vendor/go/doc/reader.go, langserver/vendor/go/doc/synopsis.go, langserver/workspace_refs.go
Currently we are getting panics sometimes running workspace/symbols due to a bug
in `go/doc`. https://github.com/golang/go/issues/17788
This change prevents panics in our pkg collector goroutines taking the whole
server down. In the future we may want to have a better approach so we don't
accidently ignore panics, but for now this lets us move forward.
Fixes https://github.com/sourcegraph/sourcegraph/issues/2053
=> Add panic handler to worker goroutines

langserver/symbol.go, langserver/symbol_test.go
https://github.com/sourcegraph/go-langserver/pull/28 incorrectly tried to apply a fix that would make `workspace/symbol` with `dir:src/net/http` for github.com/golang/go work. The reason it was incorrect, was that it was special casing handling of that repository (effectively) inside the language server, here. This became apparent as I tried to add a proper test for this case.
The more correct fix is to handle this in our build server layer. This PR includes minor code cleanup, and exposing our workspace/symbol query parsing mechanisms in order to support fixing this in our build server by rewriting the `dir:` filter portion of queries.
=> langserver: properly make workspace/symbol `dir:` filter operate on directory

langserver/handler.go, langserver/references.go
We compute this every time we answer a references query and for large workspaces
it dominates the time. However, it is static W.R.T. the workspace. In the future
when we start doing cache invalidation, this will need to be updated.
On my machine it takes subsequent references queries from 20s to 3s.
Part of #11
=> references: Cache the reverse import graph

langserver/references.go, langserver/references_test.go
Now references in the same package will be listed first, followed by
subpackages, then other packages. For other packages, if they share more
directories with the input than another package, it will be listed before. See
the test case for a concrete example.
Part of #11
=> refs: Order results by shared directories of query

langserver/handler.go, langserver/langserver_test.go
This should get a bunch of files typechecked on startup, and hopefully hide some
latency from users.
=> langserver: Run empty workspace/symbol on initialize

pkg/lsp/service.go
We also update ClientCapabilities to include the capabilities introduced in our extensions to the spec.
=> lsp: Match InitializeParams spec

langserver/internal/refs/refs.go, langserver/internal/refs/refs_test.go, langserver/langserver_test.go, langserver/workspace_refs.go
- Improve testing of `workspace/reference` generally.
- Do not emit `End` ranges that are bizarrely off or broken. Instead, emit `Start == End` and leave it as a future TODO (we do not need them right now).
- Fix an off-by-one error in the resulting `start`/`end` characters of the ranges.
- Fix a serious bug that causes the emitted filename/position for references to be VeryWrong™ / random (and add a test case).
=> workspace/reference: improve testing + fix serious bug with multiple files

langserver/hover.go, langserver/langserver_test.go
Currently, hover returns information for builtins.
This isn't the way the TypeScript language server works. It's also not useful, it simply says eg `type bool bool`. Also jump to def doesn't work on them, and neither does find references.
=> Don't return hover info builtins

langserver/tracing.go
Currently we send all telemetry events over jsonrpc. We can instead directly
send spans to our opentracing provider in production. This also helps with local
debugging/testing.
=> langserver: Use global tracer if specified

langserver/ast.go, langserver/definition.go, langserver/handler.go, langserver/hover.go, langserver/integration_test.go, langserver/internal/refs/refs.go, langserver/langserver_test.go, langserver/loader.go, langserver/references.go, langserver/workspace_refs.go, pkg/lsp/service.go, pkg/lspext/lspext.go
According to the new specification at https://github.com/sourcegraph/language-server-protocol/pull/8
Please do not merge until that PR is.
=> all: implement workspace/reference v2

langserver/definition.go, langserver/langserver_test.go, langserver/workspace_refs.go, pkg/lspext/lspext.go
Not much change, just update the LS to reflect the latest spec @ https://github.com/sourcegraph/language-server-protocol/pull/8/files which is about to be merged.
Aside from bugs, and known vendor issues (looking tomorrow), this is very close to the final implementation.
=> update to reflect latest workspace/xreferences spec

langserver/symbol.go
hi, All,
working on `documentSymbolProvider`.
any idea why `strings.ToLower(s.Location.URI)` was being called in the `score` function? i've tracked down the empty result-set to that. 1st trace is with current code, 2nd is without transforming the uri.
ta,
---
```sh
langserver-go: collectFromPkg - results.Collect - sym: {Name:NewHandler Kind:12 Location:{URI:file:///Users/mbana/go/src/github.com/sourcegraph/go-langserver/langserver/handler.go Range:{Start:{Line:21 Character:5} End:{Line:21 Character:14}}} ContainerName:langserver}
langserver-go: - score - name     : newhandler
langserver-go: - score - container: langserver
langserver-go: - score - filename : /users/mbana/go/src/github.com/sourcegraph/go-langserver/langserver/handler.go
langserver-go: - score - isVendor : false …
```
=> symbol - score - uri case:

langserver/fs.go
FilePath can currently panic, leading to deadlock since we never unlock the
mutex. We also do not need to hold the lock while using FilePath. In future, we
may make FilePath a function rather than a method since it doesn't access any
fields of h.
=> langserver: Do not hold lock for FilePath

langserver/definition.go, langserver/handler.go, langserver/langserver_test.go, langserver/workspace_refs.go, pkg/lsp/service.go, pkg/lspext/lspext.go
This mostly implements the `workspace/xreferences` third revision of the spec, as defined in the latest revision of https://github.com/sourcegraph/language-server-protocol/pull/8
The notable remaining piece left as a TODO here is to respect the `params.Files` parameter which would significantly reduce the amount of typechecking we would have to do. This is quite important, so I am tracking this issue separately and intend to follow-up on it ASAP. Without this improvement this will only really be functional for very small repositories (e.g. gorilla/mux will be OK, kubernetes not so much).
=> workspace references v3

langserver/handler_common.go, langserver/tracing.go
`opentracing.GlobalTracer()` by default is non-nil since it is the NoopTracer.
This means currently we will never use `telemetry/event`, even if we want to.
=> langserver: Correctly detect no GlobalTracer

langserver/build_context.go, langserver/fs.go, langserver/handler_shared.go
ctxvfs.NameSpace is not safe to use for concurrent read/writes (were a write is
a call to .Bind). As such we create a copy every time we want to use it in a
build.Context + it actually had some race conditions outside of that code. As
part of the perf work I am doing, I want to be able to bind to the NameSpace and
have it instantly appear to all BuildContexts. So this commit introduces
AtomicFS, a wrapper around NameSpace optimized for reads (since Bind calls are
relatively rare). The implementation avoids creating a copy every time we want a
BuildContext (common operation in our build server) + is completely safe for
concurrent access.
=> langserver: ctxvfs.NameSpace that is safe for concurrent read/writes

langserver/handler_shared.go, langserver/loader.go, langserver/loader_test.go
From some benchmarking, it seems a significant amount of time is spent in
`FindPackage`. As such, we want to be able to use more sophisticated
implementations in production. This opens the possibility for a build server to
fetch dependencies JIT, smarter vendor checks, cache package info across
commits, etc.
=> langserver: Make it possible to use a custom FindPackage

langserver/handler.go, langserver/loader.go
If we are busy typechecking something and we receive a FS command which mutates
the overlay, we can store in the cache invalid results for future hovers. This
change does not fully prevent that behaviour. However, it does make it much less
likely. The reason it could still happen is the FS tied to the bctx could be
stale. However, the amount of time that lives is low and I will fix it in a
future commit.
This change also simplifies the logic as well as removing the mutex map we had.
This single-flighting pattern is the same as the one used in the `go/loader`
pkg.
Fixes https://github.com/sourcegraph/sourcegraph/issues/2802
=> langserver: Prevent typecheck cache invalidation race

langserver/langserver_test.go, langserver/workspace_refs.go, pkg/lspext/lspext.go
See https://github.com/sourcegraph/language-server-protocol/pull/10
=> optimize workspace/xreferences (use hints)

langserver/fs.go, langserver/langserver_test.go
This seems to be a relic of ensuring our build servers correctly translate paths
to the langserver. However, the symbols are completely valid to be in a path, so
we remove the special casing for it.
Fixes #39
=> langserver: Do not panic on files with @ or :

langserver/handler.go, langserver/langserver_test.go
We incorrectly use `RootPath` as a URI. Before this change we converted unix style
absolute paths to URIs, but windows style paths would not be picked up properly.
This change should allow us to receive windows file paths.
Note: `RootPath` is deprecated in LSP 3.0 so this change is mostly to keep us working with existing systems. Once we update to LSP 3.0 (See #72) we can instead use `RootURI`, which is in fact a URI and avoid this sort of hack.
=> langserver: RootPath is always a file://

langserver/handler.go, langserver/integration_test.go, langserver/langserver_test.go, langserver/loader.go, langserver/signature.go, pkg/lsp/service.go
Experimenting with signature help provider feature. It works but pretty slow for now when comparing with vscode-go (uses `godef`)
Recording this PR to save my changes just in case
Fixes #75
=> Signature help provider

langserver/symbol.go
workspace symbol can panic if BuildContext is not set. On sourcegraph.com this
is always set, so is not an issue. However, when used as an extension this is
not set.
Fixes #70 and #69
=> langserver: Prevent panic when BuildContext is not set

langserver/format.go, langserver/handler.go, langserver/langserver_test.go
This returns a very sub-optimal `[]TextEdit`, but may suffice for now. The
`[]TextEdit` is either empty, or is 2 edits: delete all, insert formatted code.
Fixes #76
=> langserver: Initial support for formatting

langserver/symbol.go, langserver/workspace_refs.go
`buildutil.ExpandPattern` would inspect every package in the `GOPATH` and `GOROOT`.
The slowness of this is not much of a factor on sourcegraph.com, but for local
`GOPATH`s which can be large (such as my own), it is really slow. This takes
symbol search on this project on my machine from half a minute to instant.
This code is essentially the `buildutil.ExpandPattern` modified for our usecase. The idea
used can probably be submitted upstream since there are TODOs hinting at wanting this
functionality.
Previously we also incorrectly relied on `h.init.RootImportPath`, which is
technically not allowed in the langserver. In the future, we should work out
ways to prevent this accidental use of it.
Test Plan: Tested on the extensive integration tests for sourcegraph.com, which
will test both …
=> langserver: Faster package list

langserver/langserver_test.go, langserver/workspace_refs.go
This will give us much less DB entries (one/dependency referenced/repo vs. one/dependency
referenced/directory/repo).
Additionally, this will help with optimizing `workspace/xreferences` to be both performant
and accurate. It will however mean that we will likely need to add a `Limit` or other
pagination options to `workspace/xreferences`.
Also update the tests accordingly.
=> langserver: workspace/xreferences: change Go DependencyReference.Hints dir -> dirs

langserver/definition.go, langserver/handler_shared.go, langserver/loader.go, langserver/loader_test.go, langserver/symbol.go, langserver/workspace_refs.go
This allows us to also use the same FindPackage used by our typechecker.
=> langserver: Use h.FindPackage for refs loader.Config

langserver/build_context.go, langserver/definition.go, langserver/format.go, langserver/loader.go, langserver/loader_test.go, langserver/references.go, langserver/symbol.go, langserver/workspace_refs.go
This commit contains a few fixes to how we export and use our Build Context
related functions. We can greatly simplify this due to changes like AtomicFS and
changes on sourcegraph.com's build server side.
We used to export OverlayBuildContext since at one point we would use it before
doing init on sourcegraph.com's build server. Now we use the same build context
after init, so we can combine both defaultBuildContext and OverlayBuildContext
and use that everywhere. This will require a change to sourcegraph.com's
codebase.
=> langserver: Cleanup BuildContext functions

langserver/symbol.go
We don't need to keep a single `token.FileSet` while collecting symbols across
packages. This is a minor perf (lock contention) and memory (files slice)
optimization.
=> symbol: Use a new FileSet per pkg

langserver/cache.go, langserver/handler.go, langserver/loader.go, langserver/symbol.go
We experience OOMs on a semi-regular basis at the moment in sourcegraph production. This is due to our caches being unbounded. This PR is an experiment at bounding the caches. We bound them at the process level since in sourcegraph.com production we can have multiple active langserver in the same process. The initial cache sizes are estimates at what a useful size is. After experimentation with this having production traffic, I'll update the defaults.
=> langserver: Make caches bounded at the process level

langserver/handler.go, langserver/langserver_test.go, langserver/symbol.go, langserver/symbol_test.go, langserver/workspace_refs.go, pkg/lsp/service.go, pkg/lspext/lspext.go
This PR implements the extended workspace/symbol method, per the spec @ https://github.com/sourcegraph/language-server-protocol/blob/master/extension-workspace-references.md#extended-workspace-symbol-request
Additionally, it adds an `id` field to our `SymbolDescriptor` to support Sourcegraph URL-To-Definition links. See the commit message https://github.com/sourcegraph/go-langserver/commit/1dcf5891d33c375b5bf9ada073214b3b108bbb80 for details.
=> implement workspace/symbol extension

langserver/symbol.go
This may be a real issue. If so ignore this PR and lets fix the underlying
issue. However, our logs have lots of logspam with this.
```
didn't find build package name "sourcegraph.com/sourcegraph/sourcegraph/xlang/python" in parsed AST packages map[]
didn't find build package name "sourcegraph.com/sourcegraph/sourcegraph/xlang/php/src/Server" in parsed AST packages map[]
...
didn't find build package name "sourcegraph.com/sourcegraph/sourcegraph/ui/vendor/node_modules/vscode/src/vs/workbench/browser/parts/statusbar/media" in parsed AST packages map[]
didn't find build package name "sourcegraph.com/sourcegraph/sourcegraph/ui/vendor/node_modules/vscode/src/vs/workbench/parts/backup/common" in parsed AST packages map[]
didn't find build package name …
```
=> symbol: Remove missing build pkg logspam

langserver/definition.go, langserver/lsp.go, langserver/symbol.go, langserver/workspace_refs.go
Our symbol cache uses a significant amount of RAM. This change allows us to use
a more memory efficient way of storing SymbolDescriptors, but keep wire
compatibility with the extension.
=> langserver: Use memory efficient and type-safe SymbolDescriptor

langserver/workspace_refs.go
This adds a 15s timeout to workspace/xreferences which prevents some long-running requests from causing any trouble. This can happen in rarer cases with very large codebases, etc.
=> langserver: add 15s timeout to workspace/xreferences

langserver/definition.go
The return type signature of `handleDefinition` is `([]lsp.Location, error)`. If `nil, nil`
is returned then ` (*LangHandler).Handle` also returns `result interface{}` as `nil`. When
the result of a jsonrpc2 handler is nil, `jsonrpc2.HandlerWithError` [converts it into a struct](https://sourcegraph.com/github.com/sourcegraph/jsonrpc2/-/blob/handler_with_error.go#L25-28)
which is then encoded as a JSON object instead of an array. When decoding, this results in:
```
json: cannot unmarshal object into Go value of type []lspext.SymbolLocationInformation
```
Which is (obviously) bad because that looks like an error instead of 'no results'.
According to that jsonrpc2 implementation (linked above):
```
// isNilValue tests if an interface is empty, because an empty interface does
// not encode …
```
=> textDocument/xdefinition: do not return "nil" AND no error.

langserver/langserver_test.go, langserver/references.go
`AfterTypeCheck` can be called twice. This is from its docstrings:
> The function may be called twice for the same PackageInfo:
> once for the files of the package and again for the
> in-package test files.
So on the first call we wouldn't find anything defined in-package test files, so
we would set `afterTypeCheckErr`. The second call would then find it, but the
old logic would return the previous error rather than use the found object.
=> langserver: Find references defined in tests

langserver/references.go
This change causes textDocument/references on 'builtin' things (like `make` etc)
to return no results (empty array) instead of an error (`jsonrpc2: code 0 message: no package found for object builtin make`)
=> langserver: return 'no results' not an error on builtins

langserver/langserver_test.go, langserver/references.go
Previously `TypeCheckFuncBodies` excluded xtest pkgs since `obj.Pkg().Path()`
would return the path without the `_test` suffix. I'm not sure why that is, but
normalising the pkg paths to not have _test allows find references to work.
=> refs: Find refs for xtest pkg definitions

langserver/references.go
This may badly interact with using langserver in vscode, since large wait times
may be more acceptable. However, this solution is temporary until we add
cancellation support.
=> refs: Add timeout support

langserver/handler.go, langserver/references.go, langserver/symbol.go, langserver/util.go, langserver/workspace_refs.go
This should reduce the copy-paste of panic handlers.
=> langserver: Extract panic handlers into panicf

langserver/handler.go, pkg/lsp/service.go, pkg/lsp/service_test.go
The server capabilities should be equivalent to what was sent previously, but they are sent using the new, richer TextDocumentSyncOptions.
=> update to use new ServerCapabilities.TextDocumentSync field in LSP spec

pkg/lsp/service.go, pkg/lspext/cache.go
See https://github.com/sourcegraph/language-server-protocol/pull/14
=> lsp: Add cache extension structures

langserver/symbol.go
If symbol.id is present, we know we only have to inspect that pkg. This should
greatly speed up symbol queries using this extension on large repos.
=> symbol: Only inspect pkg in symbol.id

langserver/internal/refs/refs.go, langserver/langserver_test.go, langserver/workspace_refs.go
See commit descriptions for more details
=> support *_test.go files inside of workspace/xreferences

langserver/workspace_refs.go
When independently tested, the following changes passed all tests:
- https://github.com/sourcegraph/go-langserver/pull/119
- https://github.com/sourcegraph/go-langserver/pull/120
However, once merged together they began to fail tests. The reason for this is
that `AfterTypeCheck` can be invoked twice for the same package after augmentation.
Together, this meant that we introduced a race condition between the reference
searching goroutines inside `afterTypeCheck` to try to find their references (to either
package `foo` or package `foo_test`) and clear their info fields. Typically one
completes faster than the other, and subsequently the remaining one fails to find
references due to lack of package information.
We could employ a more complex pattern to prevent this, but instead I've settled …
=> langserver: do not clear package info for target packages

langserver/references.go, pkg/lspext/partial.go
This is an experiment for streaming back reference results, before the reference
operation is finished. It uses an unspecced notification called
`$/partialResult` which is a list of JSONPatch operations to apply. We stream
back results every second if we have any unsent results.
Currently the order results are sent back in is very different to what the final
result will be. It will also ignore the limit specifier. We can adjust this in
future as we see how the prototype behaves.
=> refs: Stream back partial results

langserver/hover.go, langserver/langserver_test.go
Previously we used `ast.NewCommentMap` which would suck in non-docstring related
comments. An common example of a bad docstring it would produce is `Fprintf`
would include this line at the start of the docstring
https://sourcegraph.com/github.com/golang/go@6bdb0c11c73ecf2337918d784c54f9dda2207ca7/-/blob/src/fmt/print.go#L175:1-176:1
The test case was updated to reflect this behaviour. Before this change the test
case fails.
=> hover: Use a node's Doc commentgroup

langserver/references.go
This will allow clients to ignore the actual result, and just rely on
partialResult.
=> references: Send a final partialResult

langserver/references.go
This is a more robust way to start the stream. For example, if there is an
automatic retry at some layer (true for sourcegraph.com), this will allow a
retried stream to start from scratch again.
=> reference: Initial stream op is a replace

langserver/diagnostics.go
Our support is currently broken, leading to a frustrating UX in editors.
Fixes #23
=> Disable textDocument/publishDiagnostics

langserver/internal/tools/buildutil.go, langserver/internal/tools/doc.go, langserver/internal/tools/importgraph.go, langserver/langserver_test.go, langserver/references.go, langserver/symbol.go, langserver/workspace_refs.go
In testing, this is usually the slowest part of a reference request.
This should be easily reviewed a commit at a time.
=> references: Perf improvements to importgraph building

langserver/langserver_test.go, langserver/references.go
This change is mostly refactoring and cleanup. It is intended to make it possible to use inaccurate import graphs, as well as making it possible to do multiple passes with more accurate import graphs. I have made some changes to `findReferences` which makes it responsibility clearer as well.
The follow up PR for this will actually implement the major perf improvement of using a cached import graph. I left it out of this PR in the interest of keeping this smaller.
=> references: Make it possible to use incremental import graphs

langserver/references.go, langserver/xcache.go
This should greatly speed up initial reference requests in the common case. In
sourcegraph.com production this would make us use a possibly inaccurate
importgraph to find references (computed from another commit). We still follow
up with the correct import graph, but only typecheck the package we had not
already checked. With this change and streaming, references should hopefully
almost instantaneously start streaming back, even on large repos.
=> references: Use xcache to store older importgraphs

langserver/langserver_test.go, langserver/references.go
We just need to treat `foo_test` as if it is `foo`. We do that in a few places,
but we now do it everywhere. I was concerned about possibly reporting duplicate
results, but our unit tests indicate that is not a concern.
=> references: Find refs to symbols defined in xtest

langserver/hover.go, langserver/langserver_test.go
Hardcoding the path index has a bunch of corner cases. For example look at the
test case added in this commit. It would not find doc strings in that case.
Instead we look at the first 3 in the path, which is as far as we would ever
look.
=> langserver: More robust doc extraction for hover

langserver/handler.go, langserver/references.go
I think import graph being a value + reset would lead to us overwriting the
value of the mutex => once trying to unlock a new mutex after it has finished
importing the graph.
Fixes https://github.com/sourcegraph/go-langserver/issues/146
=> references: Guard access to import graph once

langserver/fs.go
If we have quickly firing didChange notifs, the order they are processed in
can start being racey depending on the order the goroutine for each notif are
run. As such an older didChange for a document can be processed after a
newer didChange. Since we only advertise full syncing, we can rely on only using
didChange requests if they are replacing a contents with an older version
number.
=> fs: Use version field to resolve out of order FS updates

README.md, langserver/cmd/langserver-go/.gitignore, langserver/cmd/langserver-go/Dockerfile, langserver/cmd/langserver-go/Makefile, main.go
We expect going forward that users running `go get` to install go-langserver to be a very common use case. As such we can restructure the repo to make that less of a cryptic command.
Note: This changes the name of the standalone binary from `langserver-go` to `go-langserver`
cc @ramya-rao-a 
Part of #154
Fixes #135
=> Move cmd to top-level repo

langserver/references.go
We do streaming on sourcegraph.com so the timeout is not needed for that use case now. We only had the timeout because of sourcegraph.com, so we can just remove it now.
=> references: Remove hardcoded timeout

langserver/hover.go, langserver/langserver_test.go
For structs and interfaces we now include an extra hover content field containing the fields in the struct.
Fixes #168
=> hover: Include struct and interface fields

pkg/lsp/service.go, pkg/lsp/service_test.go
The LSP spec defines `MarkedString` as follows:
```
type MarkedString = string | { language: string; value: string };
```
This makes MarkedString serializable/deserializable to raw strings and adds unit tests.
=> make `MarkedString` more spec compliant

langserver/hover.go, pkg/lsp/service.go
Alternative fix for https://github.com/sourcegraph/go-langserver/pull/182
Follow-on to https://github.com/sourcegraph/go-langserver/pull/181
Confirmed that this results in docstrings being rendered in a sans-serif font in vscode 1.11.0.
cc @ramya-rao-a
=> send hover markdown as raw MarkedString

langserver/langserver_test.go, langserver/symbol.go
vscode's internal `skipLocalSymbols` option treats SymbolInformations with containerName set as locals, which are skipped. This means that when that option is used, there are no Go symbol results.
This fixes our interpretation of containerName to match vscode's assumptions.
There is minimal end-user impact. If there is no containerName, vscode shows the file path, which is actually more useful than the containerName we previously used (the package name).
=> do not emit a containerName in the SymbolInformation for package-scope defs

langserver/fs.go
Previously, if a client sent a textDocument/didClose on a dir when the FS is an overlay or virtual file system, the entire directory would be deleted. Only an erroneous client would send this, but we want to be robust to erroneous clients.
=> prevent textDocument/didXyz on dirs

langserver/workspace_refs.go
We have streaming now, so the timeout is no longer related to interactive use. Instead it is to prevent run-away resource usage.
Supersedes #189
=> bump workspace/refs timeout to a minute

langserver/references.go, langserver/workspace_refs.go
If a client does not support $/partialResult, it will just ignore the
notfications.
=> Always send $/partialResult

README.md, main.go
- This change significantly lowers memory consumption when running in editor mode (i.e. with vscode-go). From 7GB down to 4GB for a large project such as Docker.
- Additionally adds a pprof HTTP server by default, for capturing profiles easily (see README).
- Also adds an `-freeosmemory=true` flag, which when set to false can be used to disable this behavior for testing purposes (we'll also probably disable on sourcegraph.com).
Significantly helps https://github.com/sourcegraph/go-langserver/issues/178 (probably fixes entirely, but I have more improvements coming soon that I believe will lower memory consumption even further :) ).
=> significantly lower memory consumption for vscode-go users

langserver/cache.go
Typechecking used to cause linear memory growth, now it doesn't. In the docker repository, editing and hovering 5 times (to trigger typechecking) produces:
Without this change:
1. 719MB
2. 1.21GB
3. 1.89GB
4. 2.24GB
5. 2.51GB
With this change:
1. 655MB
2. 776MB
3. 787MB
4. 787MB
5. 787MB
i.e. we used to grow by about 500MB per typecheck operation, now we just idle at ~500MB.
I actually planned to remove the cache _entirely_, but with a change in direction about how I will be tackling the slowness of go to definition and hover, removing the cache entirely is not possible anymore. This is the next best thing, and is still a HUGE improvement.
Each `LangHandler` has it's own cache (see `(*LangHandler).resetCaches`), but they are backed by the same LRU cache (see `cache.go`). Every cache that …
=> Prevent linear memory growth of typechecking cache / correct cache purging

langserver/definition.go, langserver/hover.go, langserver/internal/godef/godef.go, langserver/langserver_test.go
This change adds a godef-based hover backend, similar to the godef-based
`textDocument/definition` backend added prior. The motivation for this
change is to avoid typechecking the entire program just to serve a single
`textDocument/hover` request. After this change, hover and definition are
both very quick and use little resources. Larger requests like `workspace/symbol`,
or `textDocument/references`, will continue to use more resources as they must
perform typechecking.
The output style of this hover implementation does vary from our prior
typechecking implementation in slight ways, but overall the implementation
always produces results that are on par or slightly better than our typechecking
implementation.
As with the `textDocument/definition` implementation, we should attempt …
=> langserver: add godef-based hover backend

langserver/definition.go, langserver/fs.go, langserver/handler.go, langserver/handler_common.go, langserver/integration_test.go, langserver/langserver_test.go, langserver/loader.go, langserver/loader_test.go, langserver/partial.go, langserver/references.go, langserver/symbol.go, langserver/util.go, langserver/workspace_refs.go, pkg/lsp/service.go, pkg/lsp/structures.go
In LSP, rootPath is now deprecated, and rootUri is preferred. This commit refactors internal code to pass around URIs. In most cases we were already passing URI values in fields and vars named "xyzPath".
It also adds a new helper (*InitializeParams).Root() method that implements the rootUri-over-rootPath preference.
See https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request for the relevant LSP spec section.
Test plan:
=> prefer rootUri field to rootPath

langserver/symbol.go
Prefixing the import path of `workspace/symbol` queries to the stdlib
like:
```
git://github.com/golang/go?9d3d370632ef56c1966afc67b796fa950cb347c5 "1:1" workspace/symbol {"limit":0,"symbol":{"id":"bytes/-/TrimPrefix"}}
```
Means that we end up with `/src/bytes` which is dependent upon the build
server GOROOT in use. This means that such queries would incorrectly fail
to locate symbols.
I believe (but have not 100% confirmed) that this issue was introduced
accidentally via https://github.com/sourcegraph/go-langserver/pull/198/files#diff-41a3fbc5d9dbf547085a3235ea31fd2aL329
=> langserver: fix workspace/symbol query of stdlib symbols by ID

langserver/fs.go, langserver/handler.go
Since #172 the server is able to process `textDocument/didChange` notifications in correct order, we can apply the patches without concerning that older request might overwrite a later one. This also reverts #160 .
Closes #210 .
=> Use TextDocumentSyncKind.Incremental instead of Full

langserver/fs.go, langserver/integration_test.go
The `Range.end` in LSP is exclusive. Namely, a `Range` struct specifies a range of characters from `Range.start` to the character just before `Range.end`.
Prior the fix, for example, an edit with the same start and end position will consume one character, though it shall take away none.
=> fix how end is calculated in textDocument/didChange

langserver/completion.go, langserver/completion_test.go, main.go, pkg/lsp/service.go
This adds function args as a snippet when autocompleting function calls.
When a function call completion gets selected, the function args are included in the snippet to make it easier for a user to know what arguments need to be supplied.
Here's an example using Atom as the client:
(The above is using a local dev build of [ide-go](https://github.com/ckaznocha/ide-go) with completion support added.  I will be submitting a PR to add this support to ide-go.)
=> Add function snippets to code completion results

langserver/completion.go, langserver/config.go, langserver/definition.go, langserver/handler.go, langserver/hover.go, langserver/integration_test.go, langserver/langserver_test.go, langserver/symbol.go, main.go
Following up on https://github.com/sourcegraph/go-langserver/pull/221#discussion_r160032897, this PR adds an explicit `Config` struct for grouping `langserver` config settings, and removes global config vars.
=> Add config struct

.travis.yml, langserver/langserver_test.go, langserver/loader_test.go
We need to sort out our tests, they currently fail.
=> Test tip on travis

langserver/hover.go
The optional range returned should be the range of the token the user is
hovering over. Instead we are returning the range of the definition. It isn't
trivial to return the correct range, so rather lets return nothing at all
which is more correct.
Fixes https://github.com/sourcegraph/go-langserver/issues/200
=> hover: Do not return range for godef

langserver/langserver_test.go, langserver/references.go, langserver/util/util.go
This is a lot of new code.
I've tried to document it carefully, but I will invariably have failed somewhere. Questions are very welcome, including naive questions; I will update the docs in the code with answers.
I originally wrote this change in the x/tools repo, as https://golang.org/cl/97800. Porting it to go-langserver exposed so many bugs that I've done this next round here instead, with some pretty significant changes. (What lovely tests you have!) A vigorous and skeptical review is welcome.
Once this gets a thumbs up, I will backport this new and improved version to x/tools for @alandonovan to review. If you'd prefer, we can wait to actually merge this until Alan is happy with the x/tools version as well.
There is opportunity for further straightforward optimization here by …
=> Optimize global pkglevel references

langserver/langserver_test.go
This block of code seems to have been accidentally duplicated. There is no comment explaining why it is necessary to run these tests twice.
@keegancsmith @slimsag Are you aware of any reason why these must be run twice? Just checking. If not, then it was probably a mistake.
=> langserver: remove duplicate test call (mistakenly added)

langserver/handler.go
Panic occurs when a mistakenly implemented client requests for a completion despite the langserver had set `InitializeResult.capabilities.completionProvider` to false. (see onivim/oni#1378)
This change prohibits the langserver from processing the request with an uninitiated gocode daemon and offers helpful error message.
=> completion: gracefully handle unexpected request

NOTICE, langserver/ast.go, langserver/handler.go, langserver/implementation.go, langserver/isAlias18.go, langserver/isAlias19.go, langserver/langserver_test.go, langserver/types.go, pkg/lsp/service.go, pkg/lspext/implementation.go
This PR is based on master, not no-godef as in #250.
This implements the LSP textDocument/implementation method; see https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation.
It adds the following functionality:
- on an interface, shows the types that implement it
- on a non-interface type, shows the interfaces it implements
- on an interface method, shows the methods (in implementing types) that implement it
- on a non-interface method, shows the interface methods it implements
Known problems:
- It copies a lot more code from guru.
- It could also be made more efficient in the future (it does some duplicate work right now).
- It does not let the user specify the analysis scope (as they can in guru). It uses the forward/reverse import graph.
=> support textDocument/implementation (Go interface impls queries)

Gopkg.lock, vendor/golang.org/x/tools/go/types/typeutil/imports.go, vendor/golang.org/x/tools/go/types/typeutil/map.go, vendor/golang.org/x/tools/go/types/typeutil/methodsetcache.go, vendor/golang.org/x/tools/go/types/typeutil/ui.go
Fixing error:
``` console
$ cd ~/projects/src/github.com/sourcegraph/go-langserver
$ go build -o out main.go 
langserver/implementation.go:17:2: cannot find package "golang.org/x/tools/go/types/typeutil" in any of:
/home/user/projects/src/github.com/sourcegraph/go-langserver/langserver/vendor/golang.org/x/tools/go/types/typeutil (vendor tree)
/home/user/projects/src/github.com/sourcegraph/go-langserver/vendor/golang.org/x/tools/go/types/typeutil
/nix/store/r7p21cmhq0jimq2f8c8y5sm2vqg2ap99-go-1.10/share/go/src/golang.org/x/tools/go/types/typeutil (from $GOROOT)
/home/user/projects/src/golang.org/x/tools/go/types/typeutil (from $GOPATH)
```
=> Ensure all dependencies are vendored

langserver/langserver_test.go
Under circumstances I have not adequately debugged, the
GOPATH=[tmpdir] go install -v all
used to set up test cases can fail. In my particular case, this appears
to be because something has convinced it that it absolutely has to
rewrite cmd/pprof in $GOROOT.
Reordering these (and adding the GOPATH=...) means that, if the test
fails for this reason, we get a diagnostic more specific than "exit code 1".
Signed-off-by: Seebs <seebs@seebs.net>
=> Reorder log/fatal in langserver_test. (Addresses issue #259.)

langserver/hover.go, langserver/langserver_test.go
Our godef based implementation relies on a user hovering over a token whose
def can be reported by godoc. However, this fails for variables in local
scope (very common!). I am unsure how to fix this right now other than
ignoring the error. I assume we can use the AST to construct this
information. For our other hover implementation we build this using the type
information.
Fixes https://github.com/sourcegraph/go-langserver/issues/261
=> hover: Ignore missing docs for godef based hover

langserver/definition.go, langserver/handler.go, langserver/internal/refs/refs.go, langserver/langserver_test.go, langserver/lsp.go, pkg/lsp/service.go
This adds a test case for `textdocument/typeDefinition`, and also an initial implementation.
=> Initial implementation for textdocument/typeDefinition

pkg/lsp/service.go, pkg/lsp/service_test.go
An empty slice in Go can be nil, but we don't want to marshal nil since the spec
doesn't allow it.
Fixes https://github.com/sourcegraph/go-langserver/issues/284
=> lsp: Do not marshal a nil hover contents

langserver/hover.go, langserver/langserver_test.go, langserver/util/util.go
This might address issue [269](https://github.com/sourcegraph/go-langserver/issues/269). This was a quick fix, so I'm totally open to feedback on the proper way to go about contributing here. Hope this helps!
=> concatenate line comments to field documentation

langserver/config.go, langserver/diagnostics.go, langserver/diagnostics_test.go, langserver/fs.go, langserver/handler.go, langserver/integration_test.go, langserver/langserver_test.go, langserver/loader.go, langserver/workspace_refs.go, main.go
This PR adds a very basic cache that holds diagnostics for each checked file. A file entry is removed once no more diagnostics exist for it.
An async `typecheck` now also happens on every save requests.
A simple unit test asserts the cache updating and an integration test modifies and saves files and then asserts certain diagnostics to be sent to the client.
Unfortunately it's currently based on #248 because it contains some changes that are necessary to work on my _windows_ machine 😞 
This is probably not 100% ready to be merged yet, but I think it is a good starting point 😁
=> Publish diagnostics

langserver/internal/gocode/export.go
Setting autobuild to true will allow gocode to autobuild package cache for vendor packages. I couldn't get dep vendored packages to work without this.
=> set gocode Autobuild to true, allows completion of vendor packages

README.md, langserver/config.go, langserver/format.go, langserver/lspx.go
Original code by @JeanMertz, some tweaks by me.
Fixes #272
=> Add goimports functionality to DocumentFormatting

main.go
Now that multiple format tools are available, I'd like to be able to set one from the CLI!
This PR adds a flag to set the format tool with `goimports` as the default.
=> Adds format-tool cli flag

.travis.yml, README.md, langserver/config.go, langserver/diagnostics.go, langserver/diagnostics_test.go, langserver/handler.go, langserver/integration_test.go, langserver/lint.go, langserver/lint_test.go, langserver/loader.go, langserver/lspx.go, langserver/workspace_refs.go, main.go
This pull requests adds basic support for linting.
- supports the `golint` command
- linting results are published via the diagnostics system
- entire workspace linted on initialization
- current package linted on save
=> Add support for linting

langserver/lint.go
an unnecessary panic:
https://github.com/sourcegraph/go-langserver/blob/e1b4a1b1f25a0e70582780a7da7c2c85b21614e0/langserver/lint.go#L152-L154
If source file is saved with wrong syntax, go-langserver will panic. Just printing it is enough.
=> fixed the unnecessary panic in lint

langserver/symbol.go
`range` works on possibly-nil slice/maps.
=> remove some redundant nil checks

README.md
It looks like pprof used to be enabled by default, but no longer is.
=> README: Include how to enable pprof in profiling section

Gopkg.lock, Gopkg.toml, langserver/hover.go, vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go, vendor/golang.org/x/tools/go/gcexportdata/importer.go, vendor/golang.org/x/tools/go/gcexportdata/main.go, vendor/golang.org/x/tools/go/internal/gcimporter/bexport.go, vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go, vendor/golang.org/x/tools/go/internal/gcimporter/exportdata.go, vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go, vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go, vendor/golang.org/x/tools/go/internal/gcimporter/isAlias18.go, vendor/golang.org/x/tools/go/internal/gcimporter/isAlias19.go, vendor/golang.org/x/tools/go/internal/gcimporter/newInterface10.go, vendor/golang.org/x/tools/go/internal/gcimporter/newInterface11.go, vendor/golang.org/x/tools/go/packages/doc.go, vendor/golang.org/x/tools/go/packages/external.go, vendor/golang.org/x/tools/go/packages/golist/golist.go, vendor/golang.org/x/tools/go/packages/golist/golist_fallback.go, vendor/golang.org/x/tools/go/packages/packages.go, vendor/golang.org/x/tools/go/packages/raw/raw.go
This pull request is to improve documentation preview on hover support for builtin types, functions, and variables. This fixes #174 (Hover doesn't work for builtins).
Todo:
---
1) add unit tests
2) fix incomplete type/function/variable header (append -> `func([]int, int) []int` vs.` func append([]int, int) []int`)
3) heavy refactoring to clean up code
=> builtin hover docs support

README.md, langserver/config.go, langserver/lspx.go
This PR adds an initialization option to enable diagnostics.  I didn't see a straightforward way to use the existing command line flag from my client.
=> Add a diagnosticsEnabled initialization option

langserver/hover.go
This commit adds an error check to avoid crash while accessing the result of typecheck when there is an error generated.
Encountered a panic during hover. I don't have a way to reproduce it consistently. However I think this check is necessary. Please let me know otherwise. Posting the panic st. 
```
panic serving textDocument/hover: runtime error: invalid memory address or nil pointer dereference
goroutine 75264 [running]:
third-party-source/go/src/github.com/sourcegraph/go-langserver/langserver/util.Panicf(0xa918c0, 0x10cfe90, 0xb4be8f, 0x2, 0xc0270f1248, 0x1, 0x1, 0xc0270f1258, 0x45b656)
third-party-source/go/src/github.com/sourcegraph/go-langserver/langserver/util/util.go:133 +0x93
third-party-source/go/src/github.com/sourcegraph/go-langserver/langserver.(*LangHandler).Handle.func1(0xc …
```
=> Adding an error check in handleHoverGodef

langserver/ast.go
Concrete types should go before interfaces they
implement, otherwise control will never reach them,
since type switch matching is performen sequentially,
from first case to the last one.
Found using gocritic "caseOrder" diagnostic.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> langserver: fix case order in a type switch

Gopkg.lock, buildserver/deps.go, buildserver/integration_test.go, buildserver/vfs.go, vfsutil/github_archive.go, vfsutil/github_archive_test.go, vfsutil/zip.go
- Adds support for `.netrc` (for username+password basic authentication) on zip URL fetches
- Falls back to git clone when fetching from codeload.github.com 404s so that SSH auth can be attempted
=> Support private dependencies

buildserver/build_server.go
Previously, URIs would be rewritten by finding the first dep that is a prefix **by character** of the URI's path. This changes it to prefix **by path component** to avoid considering `kubernetes/api` a prefix of `kubernetes/apimachinery`.
Fixes https://github.com/sourcegraph/sourcegraph/issues/139
=> Fix incorrect URI rewrite logic

gosrc/import_path.go
Previously, go-langserver would log errors saying it could not find some `golang_org/x/*` packages:
```
error finding package "golang_org/x/net/http/httpguts": Get http://golang_org/x/net/http/httpguts?go-get=1: dial tcp: lookup golang_org on 192.168.65.1:53: no such host
```
This did not affect the language server as far as I can tell - it only caused some distracting error messages.
See https://github.com/golang/go/issues/17326
=> Accept import paths like golang_org/x/*

Gopkg.lock, buildserver/bench_test.go, buildserver/build_server.go, buildserver/integration_test.go, buildserver/proxy_test.go, buildserver/stress_test.go, buildserver/vfs.go, diskcache/cache.go, main.go, vendor/github.com/hashicorp/errwrap/LICENSE, vendor/github.com/hashicorp/errwrap/errwrap.go, vendor/github.com/hashicorp/go-multierror/LICENSE, vendor/github.com/hashicorp/go-multierror/append.go, vendor/github.com/hashicorp/go-multierror/flatten.go, vendor/github.com/hashicorp/go-multierror/format.go, vendor/github.com/hashicorp/go-multierror/multierror.go, vendor/github.com/hashicorp/go-multierror/prefix.go, vendor/github.com/hashicorp/go-multierror/sort.go, vfsutil/cache.go, vfsutil/zip.go
Previously, cache entries were never being evicted.
Now, go-langserver calls evicts cache entries oldest-first until the `MaxCacheSizeBytes` is satisfied when a connection is closed (e.g. WebSocket disconnect). `BuildServer` keeps track of archives it has opened (only the current repository for now), and implement `io.Closer` by `Close()`ing archives that it had opened, which in turn calls `Evict()`.
Fixes https://github.com/sourcegraph/sourcegraph-go/issues/20
=> Evict cache entries when the connection closes

vfsutil/zip.go
Prior to this change, the cache key was the full URL, including whatever username:password was set (e.g. the Sourcegraph access token).
After this change, the cache key will be the URL but with empty username:password.
This will increase the probability of a cache hit because each repo@revision will be fetched once and used by any user.
A `HEAD` request is still made for each user x repo@revision pair to make sure the user has access to the repository contents.
- Helps fix https://sourcegraph.slack.com/archives/C0C324C91/p1554154297030300
- Helps fix https://sourcegraph.slack.com/archives/C0C324C91/p1554159963034900
- Helps `fix` https://github.com/sourcegraph/sourcegraph/issues/1940
cc @beyang just FYI, no action necessary
=> Do not include access token in cache key when fetching zip archives

buildserver/deps.go
Some users have import paths that look like `example.com/user/repo.git` and the repository name on Sourcegraph is `example.com/user/repo` (without `.git`).
Prior to this change, go-langserver would attempt to fetch `example.com/user/repo.git` and get a 404.
After this change, go-langserver will fetch `example.com/user/repo` instead. This will break when the repository name on Sourcegraph has a `.git` suffix. @beyang Does that seem acceptable? Alternatively, go-langserver could try the original (with `.git`) and then fallback to dropping the suffix.
This worked in Sourcegraph 2.x probably because the repository contents were obtained through lsp-proxy and gitserver, rather than the raw API.
=> Strip .git suffix from dependencies

README.md, buildserver/environment.go
These were removed from the Sourcegraph.com docs in https://github.com/sourcegraph/sourcegraph/pull/584 but still apply to go-langserver.
Fixes https://github.com/sourcegraph/go-langserver/issues/365
=> Docs: restore docs from Sourcegraph.com

langserver/hover.go
CI is failing because of this https://ci.appveyor.com/project/sourcegraph/go-langserver/builds/24438368
> langserver\hover.go:503:18: Errorf format %q has arg pkgs of wrong type map[string]*go/ast.Package
I think this broke because the default Appveyor Go version was changed from 1.11 to 1.12.
=> Fix format string

buildserver/vfs.go
Passing both `zipURL` and `zipURLTemplate` is redundant. `zipURL` can be derived by instantiating the `zipURLTemplate` with `originalRootURI`.
This adds support for clients that omit `zipURL` and only provide `zipURLTemplate`. This is part of [simplifying lsp-client's communication with go-langserver](https://docs.google.com/document/d/1rFcwzKaEf2WtMJBZAc4L1LxBJqgKAduI8PMvjnNowE0/edit#heading=h.44mn607i8nf4).
=> Derive zip URL from template

buildserver/environment.go, langserver/internal/refs/refs_test.go
Rewrites Go import paths for the `log15` package from `gopkg.in/inconshreveable/log15.v2` to `github.com/inconshreveable/log15` using [Comby](https://comby.dev/)
[_Created by Sourcegraph batch change `christine/rewrite-log15-import`._](https://demo.sourcegraph.com/users/christine/batch-changes/rewrite-log15-import)
=> Fix import path for log15 package
